pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                sh 'mvn --version'
                sh 'java --version'
                
                // Create the Java file inside the container
                sh """
                echo 'public class HelloWorld {
                    public static void main(String[] args) {
                        System.out.println("Hello, World from Java!");
                    }
                }' > HelloWorld.java
                """

                // Compile and run the Java file
                sh 'javac HelloWorld.java'
                sh 'java HelloWorld'
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
